/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package learning;

import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author shana
 */
public class MenuDemo extends javax.swing.JFrame {

    /**
     * Creates new form MenuDemo
     */
    public MenuDemo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg1 = new javax.swing.ButtonGroup();
        mnPopup = new javax.swing.JPopupMenu();
        mnBackground = new javax.swing.JMenu();
        mnRed = new javax.swing.JMenuItem();
        mnBlue = new javax.swing.JMenuItem();
        mnForeground = new javax.swing.JMenu();
        mnYellow = new javax.swing.JMenuItem();
        mnPink = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt1 = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnFile = new javax.swing.JMenu();
        mnOpen = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnClose = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        mnQuit = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnCustom = new javax.swing.JMenu();
        mnCustom1 = new javax.swing.JCheckBoxMenuItem();
        mnCustom2 = new javax.swing.JMenu();
        mnCustom21 = new javax.swing.JRadioButtonMenuItem();
        mnCustom22 = new javax.swing.JRadioButtonMenuItem();

        mnBackground.setText("Background");

        mnRed.setBackground(new java.awt.Color(255, 51, 51));
        mnRed.setOpaque(true);
        mnRed.setPreferredSize(new java.awt.Dimension(100, 100));
        mnRed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnRedActionPerformed(evt);
            }
        });
        mnBackground.add(mnRed);

        mnBlue.setBackground(new java.awt.Color(153, 204, 255));
        mnBlue.setOpaque(true);
        mnBlue.setPreferredSize(new java.awt.Dimension(100, 100));
        mnBlue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnBlueActionPerformed(evt);
            }
        });
        mnBackground.add(mnBlue);

        mnPopup.add(mnBackground);

        mnForeground.setText("Foreground");

        mnYellow.setBackground(new java.awt.Color(255, 255, 102));
        mnYellow.setOpaque(true);
        mnYellow.setPreferredSize(new java.awt.Dimension(100, 100));
        mnYellow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnYellowActionPerformed(evt);
            }
        });
        mnForeground.add(mnYellow);

        mnPink.setBackground(new java.awt.Color(255, 153, 204));
        mnPink.setOpaque(true);
        mnPink.setPreferredSize(new java.awt.Dimension(100, 100));
        mnPink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnPinkActionPerformed(evt);
            }
        });
        mnForeground.add(mnPink);

        mnPopup.add(mnForeground);
        mnForeground.getAccessibleContext().setAccessibleParent(mnPopup);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txt1.setColumns(20);
        txt1.setRows(5);
        txt1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txt1MouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(txt1);

        mnFile.setText("File");

        mnOpen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mnOpen.setText("Open");
        mnOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnOpenActionPerformed(evt);
            }
        });
        mnFile.add(mnOpen);
        mnFile.add(jSeparator2);

        mnClose.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mnClose.setText("Close");
        mnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCloseActionPerformed(evt);
            }
        });
        mnFile.add(mnClose);
        mnFile.add(jSeparator3);

        mnQuit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mnQuit.setText("Quit");
        mnQuit.setToolTipText("");
        mnQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnQuitActionPerformed(evt);
            }
        });
        mnFile.add(mnQuit);
        mnFile.add(jSeparator1);

        jMenuBar1.add(mnFile);

        mnCustom.setText("Custom");

        mnCustom1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mnCustom1.setSelected(true);
        mnCustom1.setText("Custom 1");
        mnCustom1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCustom1ActionPerformed(evt);
            }
        });
        mnCustom.add(mnCustom1);

        mnCustom2.setText("Custom 2");

        bg1.add(mnCustom21);
        mnCustom21.setText("Custom21");
        mnCustom21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCustom21ActionPerformed(evt);
            }
        });
        mnCustom2.add(mnCustom21);

        bg1.add(mnCustom22);
        mnCustom22.setText("Custom 22");
        mnCustom22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCustom22ActionPerformed(evt);
            }
        });
        mnCustom2.add(mnCustom22);

        mnCustom.add(mnCustom2);

        jMenuBar1.add(mnCustom);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnOpenActionPerformed
        JOptionPane.showMessageDialog(this, "Menu Open is clicked.");
    }//GEN-LAST:event_mnOpenActionPerformed

    private void mnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCloseActionPerformed
        JOptionPane.showMessageDialog(this, "Menu Close is clicked.");
    }//GEN-LAST:event_mnCloseActionPerformed

    private void mnQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnQuitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnQuitActionPerformed

    private void mnCustom1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCustom1ActionPerformed
        if (this.mnCustom1.isSelected()) {
            JOptionPane.showMessageDialog(this, "Menu Custom 1 is selected.");
        } else {
            JOptionPane.showMessageDialog(this, "Menu Custom 1 is de-selected.");
        }
    }//GEN-LAST:event_mnCustom1ActionPerformed

    private void mnCustom21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCustom21ActionPerformed
        if (this.mnCustom21.isSelected()) {
            JOptionPane.showMessageDialog(this, "Menu Custom 21 is selected.");
        }
    }//GEN-LAST:event_mnCustom21ActionPerformed

    private void mnCustom22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCustom22ActionPerformed
        if (this.mnCustom22.isSelected()) {
            JOptionPane.showMessageDialog(this, "Menu Custom 22 is selected.");
        }
    }//GEN-LAST:event_mnCustom22ActionPerformed

    private void txt1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt1MouseReleased
        if (evt.isPopupTrigger()) {
            this.mnPopup.show(this.txt1, evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_txt1MouseReleased

    private void mnRedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnRedActionPerformed
        this.txt1.setBackground(Color.RED);
    }//GEN-LAST:event_mnRedActionPerformed

    private void mnBlueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnBlueActionPerformed
        this.txt1.setBackground(Color.BLUE);
    }//GEN-LAST:event_mnBlueActionPerformed

    private void mnPinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnPinkActionPerformed
        this.txt1.setForeground(Color.PINK);
    }//GEN-LAST:event_mnPinkActionPerformed

    private void mnYellowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnYellowActionPerformed
        this.txt1.setForeground(Color.YELLOW);
    }//GEN-LAST:event_mnYellowActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MenuDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MenuDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MenuDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MenuDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
        //</editor-fold>

        FlatLightLaf.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // Set Flatlaf Look and Feel
//                try {
//                    UIManager.setLookAndFeel("com.formdev.flatlaf.FlatDarkLaf");
//                } catch (Exception e) {
//                    e.toString();
//                }
//                JFrame.setDefaultLookAndFeelDecorated(true);
                new MenuDemo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bg1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JMenu mnBackground;
    private javax.swing.JMenuItem mnBlue;
    private javax.swing.JMenuItem mnClose;
    private javax.swing.JMenu mnCustom;
    private javax.swing.JCheckBoxMenuItem mnCustom1;
    private javax.swing.JMenu mnCustom2;
    private javax.swing.JRadioButtonMenuItem mnCustom21;
    private javax.swing.JRadioButtonMenuItem mnCustom22;
    private javax.swing.JMenu mnFile;
    private javax.swing.JMenu mnForeground;
    private javax.swing.JMenuItem mnOpen;
    private javax.swing.JMenuItem mnPink;
    private javax.swing.JPopupMenu mnPopup;
    private javax.swing.JMenuItem mnQuit;
    private javax.swing.JMenuItem mnRed;
    private javax.swing.JMenuItem mnYellow;
    private javax.swing.JTextArea txt1;
    // End of variables declaration//GEN-END:variables
}
